HCI/urls.py
from django.urls import path

from HCI.views.model_views import *

university_url_patterns = [
    path('add', UniversityCreateView.as_view(), name='add'),
    path('list-view', UniversityListView.as_view(), name='list_view'),
    path('<int:pk>/', UniversityDetailView.as_view(), name='detail_view'),
    path('<int:pk>/update', UniversityUpdateView.as_view(), name='update'),
    path('auto-complete', UniversityAutoComplete.as_view(), name='auto_complete'),
    path('state-auto-complete', StateAutoComplete.as_view(), name='state_auto_complete'),
]

course_url_patterns = [
    path('add', CourseCreateView.as_view(), name='add'),
    path('list-view', CourseListView.as_view(), name='list_view'),
    path('<int:pk>/', CourseDetailView.as_view(), name='detail_view'),
    path('<int:pk>/update', CourseUpdateView.as_view(), name='update'),
    path('auto-complete', CourseEquivalentAutoComplete.as_view(), name='auto_complete')
]

HCI_Course/urls.py
from django.contrib import admin
from django.urls import path, include

from HCI.urls import university_url_patterns, course_url_patterns
from HCI.views import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'))),
    path('university/', include((university_url_patterns, 'HCI'), namespace='university')),
    path('course/', include((course_url_patterns, 'HCI'), namespace='course')),
    path('charts/', include(('charts.urls', 'charts'))),
    path('report/', include(('report.urls', 'report'))),
    path('message/', include(('message.urls', 'message'))),
    path('', views.homepage, name='homepage'),
]

HCI/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
import string
import random


# Create your models here.
from HCI.choices import CATEGORY_CHOICES, COUNTRY_CHOICES, get_all_states


def generate_slug():
    choices = string.ascii_letters + string.digits
    return ''.join(random.choice(choices) for i in range(10))


class University(models.Model):
    user = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100, verbose_name="University Name", unique=True, null=False, blank=False)
    short_name = models.CharField(max_length=100, verbose_name="University Short Name", null=False, blank=False)
    country = models.CharField(
        max_length=100, verbose_name="University Country", choices=COUNTRY_CHOICES, null=False, blank=True)
    state = models.CharField(
        max_length=100, verbose_name="University State", choices=get_all_states(), null=False, blank=True)
    city = models.CharField(
        max_length=100, verbose_name="University City", null=False, blank=True)

    def __str__(self):
        return str(self.name)


class Course(models.Model):
    slug = models.CharField(max_length=10, default=generate_slug, verbose_name="Slug", null=False, blank=False,
                            editable=False, unique=True)
    user = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=500, verbose_name="Course Name", null=False, blank=True)
    code = models.CharField(max_length=100, verbose_name="Course Code", null=False, blank=True)
    university = models.ForeignKey(University, verbose_name="University", on_delete=models.CASCADE)
    description = models.TextField(verbose_name="Course Description", null=False, blank=True)
    category = models.CharField(max_length=500, verbose_name="Category Name", choices=CATEGORY_CHOICES, null=False,
                                blank=False)

    url = models.URLField(verbose_name="Most Recent Course Website", null=True, blank=True)
    prerequisites = models.CharField(verbose_name="Course Prerequisites", max_length=500, null=True, blank=True)
    core_for_major = models.BooleanField(verbose_name="Core for Major?", null=False)
    last_taught = models.DateField(verbose_name="Last Taught", null=True, blank=True)
    instructor = models.CharField(verbose_name="Most Recent Instructor", max_length=100, null=False, blank=True)
    learning_goals = models.TextField(verbose_name="Learning outcome/goals", null=False, blank=True)
    complete = models.BooleanField(verbose_name="Is it complete", default=False)
    verified = models.BooleanField(verbose_name="Is it verified", default=False)

    equivalent = models.ManyToManyField('self', symmetrical=True, blank=True)

    def __str__(self):
        return "{} ({}) in {}".format(self.name, self.code, self.university)

    class Meta:
        unique_together = ['code', 'university']


class Criteria(models.Model):
    name = models.CharField(verbose_name="Criteria Name", max_length=100, null=False, blank=True)
    weight = models.FloatField(verbose_name="Criteria Weight")
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)

    def __str__(self):
        return "{} {} in {}".format(self.name, self.weight, self.course.name)

    class Meta:
        unique_together = ['name', 'course']


class Topic(models.Model):
    week = models.IntegerField(verbose_name="Number of the Week in Which This Topic Is Taught", null=False, blank=True)
    description = models.CharField(max_length=800, verbose_name="Topic Description", blank=True)
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)

    def __str__(self):
        return "topic of week {} for {}".format(self.week, self.course.name)

    class Meta:
        unique_together = ['week', 'course']

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class MyUser(AbstractUser):
    @property
    def new_messages_count(self):
        return self.received_messages.filter(read=False).count()

    @property
    def has_name(self):
        return self.first_name is not None and self.first_name != ""

    @property
    def has_complete_profile(self):
        return self.has_name

charts/models.py
from django.db import models

# Create your models here.

message/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name="Sender User", on_delete=models.SET_NULL, null=True,
                               db_index=True,
                               related_name='send_messages')
    receiver = models.ForeignKey(get_user_model(), verbose_name="Receiver User", on_delete=models.CASCADE, null=False,
                                 db_index=True, related_name='received_messages')
    message = models.TextField(verbose_name="The message text")
    read = models.BooleanField(default=False, db_index=True)
    reply_to = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='replies', null=True, blank=True)

    def read_message(self):
        if not self.read:
            self.read = True
            self.save()

HCI/views/account_views.py
from django.contrib.auth import login
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic import UpdateView

from HCI.forms import SignupForm
from HCI.utils.email_functions import send_activation_email, account_activation_token_generator, send_password_reset_email


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            send_activation_email(request, user)
            return render(request, 'message.html', {
                'title': "Sign Up Successful",
                'message': "Thank you for signing up. An activation link is sent to your email. Please Activate your "
                           "account using that link",
            })
    else:
        form = SignupForm()
    return render(request, 'account/register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, 'message.html', {
            'title': "Your Account is Activated",
            'message': 'Thank you for your email confirmation. Now you can login your account.',
        })
    else:
        return render(request, 'message.html', {
            'title': "Something went wrong",
            'message': 'Activation link is invalid!',
        })


class UserProfileView(UpdateView):
    model = User
    template_name = 'account/profile.html'
    success_url = reverse_lazy('profile')
    fields = ['username', 'first_name', 'last_name', 'email']

    def get_object(self, queryset=None):
        return self.request.user


class PasswordChangeView2(PasswordChangeView):
    success_url = reverse_lazy('account:password_change_done')
    template_name = 'account/password_change.html'


def password_change_done_view(request):
    return render(request, 'message.html', {
        'title': "Password Changed",
        'message': 'Your password has been successfully changed!',
    })


def forgot_password_view(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            users = form.get_users(email)
            for user in users:
                send_password_reset_email(request, user)
            return render(request, 'message.html', {
                'title': "Password Reset Email Sent",
                'message': 'Your password reset request has been sent to your email, '
                           'please follow the further instruction in your email',
            })
    else:
        form = PasswordResetForm()
    return render(request, 'account/forgot.html', {'form': form})


def password_reset_view(request, uidb64, token):
    def get_user():
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and default_token_generator.check_token(user, token):
            return user
        return None

    def bad_token():
        return render(request, 'message.html', {
            'title': "Something Went Wrong :(",
            'message': 'Your token in invalid',
        })

    if request.method == 'POST':
        user = get_user()
        if not user:
            return bad_token()

        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'message.html', {
                'title': "Your Password Has Been Reset",
                'message': 'Your password has been reset successfully, please login with your new password',
            })
    else:
        user = get_user()
        if not user:
            return bad_token()
        form = SetPasswordForm(user)
    return render(request, 'account/password_reset.html', {'form': form})

HCI/views/model_views.py
from dal import autocomplete
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DetailView, UpdateView

from HCI.choices import get_all_states, ALL_STATES
from HCI.forms import CourseCreateForm, UniversityCreateForm, CourseFilterForm
from HCI.models import University, Course


@method_decorator(login_required, name='dispatch')
class UniversityCreateView(CreateView):
    model = University
    template_name = 'models/university_create.html'
    success_url = reverse_lazy('university:add')
    form_class = UniversityCreateForm

    def form_valid(self, form):
        response = super(UniversityCreateView, self).form_valid(form)

        self.object.user = self.request.user
        self.object.save()

        return response


@method_decorator(login_required, name='dispatch')
class CourseCreateView(CreateView):
    model = Course
    template_name = 'models/course_create.html'
    success_url = reverse_lazy('course:add')
    form_class = CourseCreateForm

    def form_valid(self, form):
        response = super(CourseCreateView, self).form_valid(form)

        self.object.user = self.request.user
        self.object.save()

        return response


class CourseListView(ListView):
    model = Course
    template_name = 'models/course_list_view.html'

    def get_queryset(self):
        my_courses = self.request.GET.get('my_courses', None)
        query = self.request.GET.get('query', None)
        county = self.request.GET.get('country', None)
        university = self.request.GET.get('university', None)

        q = Q()

        if my_courses:
            user = self.request.user
            q = q & Q(user=user)

        if query:
            q = q & (Q(name__contains=query) | Q(code__contains=query))

        if county and county != 'ALL':
            q = q & Q(university__country=county)

        if university:
            q = q & Q(university=university)

        return Course.objects.filter(q).all()

    def get_context_data(self, **kwargs):
        context = super(CourseListView, self).get_context_data(**kwargs)
        object_list = context['object_list']

        for object in object_list:
            object.editable = True if object.user == self.request.user else False

        context['form'] = CourseFilterForm(self.request.GET)

        return context


class CourseDetailView(DetailView):
    model = Course
    template_name = 'models/course_detail_view.html'

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)

        object = context['object']
        object.editable = True if object.user == self.request.user else False

        return context


class CourseUpdateView(UserPassesTestMixin, UpdateView):

    def test_func(self):
        return self.get_object().user == self.request.user

    model = Course
    template_name = 'models/course_update.html'
    fields = ['name', 'code', 'university', 'description', 'category', 'url', 'prerequisites', 'core_for_major',
              'last_taught', 'instructor', 'learning_goals', 'equivalent']

    def get_success_url(self):
        return reverse('course:detail_view', None, [self.kwargs.get('pk'), ])


class UniversityListView(ListView):
    model = University
    template_name = 'models/university_list_view.html'


class UniversityDetailView(DetailView):
    model = University
    template_name = 'models/university_detail_view.html'


class UniversityUpdateView(UpdateView):
    model = University
    template_name = 'models/university_update.html'
    fields = ['name', 'short_name']

    def get_success_url(self):
        return reverse('university:detail_view', None, [self.kwargs.get('pk'), ])


class UniversityAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = University.objects.all()
        if self.q:
            qs = qs.filter(name__contains=self.q)
        return qs


class CourseEquivalentAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Course.objects.all()
        if self.q:
            qs = qs.filter(name__contains=self.q)
        return qs


class StateAutoComplete(autocomplete.Select2ListView):

    def get_list(self):
        country = self.forwarded.get('country', None)
        if not country or country not in ALL_STATES:
            return []
        return ALL_STATES[country].items()

    def autocomplete_results(self, results):
        token = self.q or ""
        return [(x, y) for (x, y) in results if token.lower() in (x + y).lower()]

    def results(self, results):
        """Return the result dictionary."""
        return [dict(id=x[0], text=x[1]) for x in results]

HCI/views/views.py
from django.shortcuts import render


# Create your views here.
from HCI.models import Course
from charts.views import get_criteria_chart_data_dict


def homepage(request):

    courses = Course.objects.all()[:4]

    sample_data_chart_data_dict = get_criteria_chart_data_dict()

    return render(request, "homepage.html", {
        'courses': courses,
        'sample_chart_labels': sample_data_chart_data_dict['labels'],
        'sample_chart_data': sample_data_chart_data_dict['data'],
    })

HCI/templates/models/course_create.html
{% extends 'base.html' %}

{% block title %}Add Course{% endblock %}

{% block script %}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h2>Create Course</h2>
    <form method="post">
        {% csrf_token %}

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group col-md-6">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {{ field.label_tag }}
                {{ field }}
                {% autoescape off %}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                {% endautoescape %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary" id="menu-toggle">Create</button>
    </form>
{% endblock %}

HCI/templates/models/course_detail_view.html
{% extends 'base.html' %}

{% block title %}Course Detail{% endblock %}

{% block content %}
    <h2>Course</h2>

    <div class="col-md-6 mb-3">
        <label for="University Name">Name</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.name }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="Short Name">Code</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.code }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">University</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.university.name }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="description">Description</label>
        <textarea disabled class="form-control" name="description" cols="40" rows="10" id="description">
            {{ course.description }}
        </textarea>
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Category</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.category }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="id_url">Most Recent Course Website</label>
        <input disabled class="form-control" type="url" name="url"
               value="{{ course.url }}"
               maxlength="200" id="id_url">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Prerequisites</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.prerequisites }}">
    </div>

    <p>
        <label for="id_core_for_major">Core for Major</label>
        <input disabled class="form-control" type="checkbox" name="core_for_major" id="id_core_for_major"
                {% if course.core_for_major %} checked {% endif %}>
    </p>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Last Taught</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.last_taught.year }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Instructor</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.instructor }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="description">Learning Goals / Outcome</label>
        <textarea disabled class="form-control" name="description" cols="40" rows="10" id="description">
            {{ course.learning_goals }}
        </textarea>
    </div>

    <div class="col-md-6 mb-3">
        {% if course.editable %}
            <button class="btn btn-warning"
                    onclick="window.location.href='{% url 'course:update' course.pk %}'">edit
            </button>
        {% else %}
            <button class="btn btn-warning" disabled title="You Cannot Edit This Course"
                    onclick="window.location.href='{% url 'course:update' course.pk %}'">edit
            </button>
        {% endif %}
    </div>
    <div class="col-md-6 mb-3">
        <button class="btn btn-danger"
                onclick="window.location.href='{% url 'report:course'%}?course={{ course.pk }}'">report
        </button>

    </div>




{% endblock %}

HCI/templates/models/course_list_view.html
{% extends 'base.html' %}

{% block title %}Courses{% endblock %}

{% block style %}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h2>Courses</h2>

    <div class="my-3">
        <button class="btn btn-primary"
                onclick="window.location.href = '{% url 'course:list_view' %}?my_courses=true'">
            My Courses
        </button>
        <button class="btn btn-primary" onclick="window.location.href = '{% url 'course:list_view' %}'">All
            Courses
        </button>
        <button class="btn btn-primary float-right" onclick="window.location.href = '{% url 'course:add' %}'">
            Add
            Course
        </button>
    </div>


    <form method="get">
        <div class="form-row">
            <div class="form-group col">
                <label class="sr-only">Search</label>
                {{ form.query }}
            </div>
            <div class="col-1">
                <button type="submit" class="btn btn-primary float-right">Search</button>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col">
                {{ form.country.label_tag }}
                {{ form.country }}
            </div>
            <div class="form-group col">
                {{ form.university.label_tag }}
                {{ form.university }}
            </div>
            <div class="col-1 my-auto">
                <button type="submit" class="btn btn-primary mb-2 float-right">Filter</button>
            </div>
        </div>

    </form>

    {% include 'course/course_list_table_snippet.html' %}
{% endblock %}

HCI/templates/models/course_update.html
{% extends 'base.html' %}

{% block title %}Update Course{% endblock %}

{% block content %}
    <h2>Update Course</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" id="menu-toggle">Update</button>
    </form>
{% endblock %}

HCI/templates/models/university_create.html
{% extends 'base.html' %}

{% block title %}Add University{% endblock %}

{% block script %}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h2>Create University</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" id="menu-toggle">Create</button>
    </form>
{% endblock %}

HCI/templates/models/university_detail_view.html
{% extends 'base.html' %}

{% block title %}University Detail{% endblock %}

{% block content %}
    <h2>University</h2>

    <div class="col-md-6 mb-3">
        <label for="University Name">Name</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ university.name }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="Short Name">Short Name</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ university.short_name }}">
    </div>
    <div class="col-md-6 mb-3">
        <button class="btn btn-warning" onclick="window.location.href='{% url 'university:update' university.pk %}'">edit</button>
    </div>
    <div class="col-md-6 mb-3">
        <button class="btn btn-danger" onclick="window.location.href='{% url 'report:university'%}?university={{ university.pk }}'">report</button>
    </div>

{% endblock %}

HCI/templates/models/university_list_view.html
{% extends 'base.html' %}

{% block title %}Universities{% endblock %}

{% block content %}
    <h2>Universities</h2>

    <button class="btn btn-primary" onclick="window.location.href = '{% url 'university:add' %}'">Add University</button>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Short Name</th>
            <th scope="col">Details</th>
            <th scope="col">Edit</th>
            <th scope="col">Report</th>
        </tr>
        </thead>
        <tbody>
        {% for uni in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ uni.name }}</td>
                <td>{{ uni.short_name }}</td>
                <td><button class="btn btn-primary" onclick="window.location.href='{% url 'university:detail_view' uni.pk %}'">details</button></td>
                <td><button class="btn btn-warning" onclick="window.location.href='{% url 'university:update' uni.pk %}'">edit</button></td>
                <td><button class="btn btn-danger" onclick="window.location.href='{% url 'report:university' %}?university={{ uni.pk }}'">report</button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

HCI/templates/models/university_update.html
{% extends 'base.html' %}

{% block title %}Update University{% endblock %}

{% block content %}
    <h2>Update University</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" id="menu-toggle">Update</button>
    </form>
{% endblock %}