HCI/urls.py
from django.urls import path

from HCI.views.model_views import *

university_url_patterns = [
    path('add', UniversityCreateView.as_view(), name='add'),
    path('list-view', UniversityListView.as_view(), name='list_view'),
    path('<int:pk>/', UniversityDetailView.as_view(), name='detail_view'),
    path('<int:pk>/update', UniversityUpdateView.as_view(), name='update'),
    path('auto-complete', UniversityAutoComplete.as_view(), name='auto_complete'),
    path('state-auto-complete', StateAutoComplete.as_view(), name='state_auto_complete'),
]

course_url_patterns = [
    path('add', CourseCreateView.as_view(), name='add'),
    path('list-view', CourseListView.as_view(), name='list_view'),
    path('<int:pk>/', CourseDetailView.as_view(), name='detail_view'),
    path('<int:pk>/update', CourseUpdateView.as_view(), name='update'),
    path('auto-complete', CourseEquivalentAutoComplete.as_view(), name='auto_complete')
]

HCI_Course/urls.py
from django.contrib import admin
from django.urls import path, include

from HCI.urls import university_url_patterns, course_url_patterns
from HCI.views import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'))),
    path('university/', include((university_url_patterns, 'HCI'), namespace='university')),
    path('course/', include((course_url_patterns, 'HCI'), namespace='course')),
    path('charts/', include(('charts.urls', 'charts'))),
    path('report/', include(('report.urls', 'report'))),
    path('message/', include(('message.urls', 'message'))),
    path('', views.homepage, name='homepage'),
]

message/urls.py
from django.urls import path

from message.views import MessageListView, MessageDetailView, message_delete_view

urlpatterns = [
    path('list-view', MessageListView.as_view(), name='list_view'),
    path('', MessageDetailView.as_view(), name='detail'),
    path('delete', message_delete_view, name='delete'),
]

HCI/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
import string
import random


# Create your models here.
from HCI.choices import CATEGORY_CHOICES, COUNTRY_CHOICES, get_all_states


def generate_slug():
    choices = string.ascii_letters + string.digits
    return ''.join(random.choice(choices) for i in range(10))


class University(models.Model):
    user = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100, verbose_name="University Name", unique=True, null=False, blank=False)
    short_name = models.CharField(max_length=100, verbose_name="University Short Name", null=False, blank=False)
    country = models.CharField(
        max_length=100, verbose_name="University Country", choices=COUNTRY_CHOICES, null=False, blank=True)
    state = models.CharField(
        max_length=100, verbose_name="University State", choices=get_all_states(), null=False, blank=True)
    city = models.CharField(
        max_length=100, verbose_name="University City", null=False, blank=True)

    def __str__(self):
        return str(self.name)


class Course(models.Model):
    slug = models.CharField(max_length=10, default=generate_slug, verbose_name="Slug", null=False, blank=False,
                            editable=False, unique=True)
    user = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=500, verbose_name="Course Name", null=False, blank=True)
    code = models.CharField(max_length=100, verbose_name="Course Code", null=False, blank=True)
    university = models.ForeignKey(University, verbose_name="University", on_delete=models.CASCADE)
    description = models.TextField(verbose_name="Course Description", null=False, blank=True)
    category = models.CharField(max_length=500, verbose_name="Category Name", choices=CATEGORY_CHOICES, null=False,
                                blank=False)

    url = models.URLField(verbose_name="Most Recent Course Website", null=True, blank=True)
    prerequisites = models.CharField(verbose_name="Course Prerequisites", max_length=500, null=True, blank=True)
    core_for_major = models.BooleanField(verbose_name="Core for Major?", null=False)
    last_taught = models.DateField(verbose_name="Last Taught", null=True, blank=True)
    instructor = models.CharField(verbose_name="Most Recent Instructor", max_length=100, null=False, blank=True)
    learning_goals = models.TextField(verbose_name="Learning outcome/goals", null=False, blank=True)
    complete = models.BooleanField(verbose_name="Is it complete", default=False)
    verified = models.BooleanField(verbose_name="Is it verified", default=False)

    equivalent = models.ManyToManyField('self', symmetrical=True, blank=True)

    def __str__(self):
        return "{} ({}) in {}".format(self.name, self.code, self.university)

    class Meta:
        unique_together = ['code', 'university']


class Criteria(models.Model):
    name = models.CharField(verbose_name="Criteria Name", max_length=100, null=False, blank=True)
    weight = models.FloatField(verbose_name="Criteria Weight")
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)

    def __str__(self):
        return "{} {} in {}".format(self.name, self.weight, self.course.name)

    class Meta:
        unique_together = ['name', 'course']


class Topic(models.Model):
    week = models.IntegerField(verbose_name="Number of the Week in Which This Topic Is Taught", null=False, blank=True)
    description = models.CharField(max_length=800, verbose_name="Topic Description", blank=True)
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)

    def __str__(self):
        return "topic of week {} for {}".format(self.week, self.course.name)

    class Meta:
        unique_together = ['week', 'course']

message/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.


class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name="Sender User", on_delete=models.SET_NULL, null=True,
                               db_index=True,
                               related_name='send_messages')
    receiver = models.ForeignKey(get_user_model(), verbose_name="Receiver User", on_delete=models.CASCADE, null=False,
                                 db_index=True, related_name='received_messages')
    message = models.TextField(verbose_name="The message text")
    read = models.BooleanField(default=False, db_index=True)
    reply_to = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='replies', null=True, blank=True)

    def read_message(self):
        if not self.read:
            self.read = True
            self.save()

HCI/forms.py
from dal import autocomplete
from django import forms
from django.forms import TextInput, Textarea, Select, widgets
from django.urls import reverse_lazy

from HCI import choices
from HCI.choices import get_all_states, COUNTRY_CHOICES
from HCI.models import Course, University
from HCI.widgets import MyDateInput


class CourseFilterForm(forms.Form):
    query = forms.CharField(
        required=False,
        widget=widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Search in our courses...',
        })
    )

    country = forms.ChoiceField(
        required=False,
        choices=[('ALL', 'ALL')] + COUNTRY_CHOICES,
        widget=Select(
            attrs={
                'class': 'form-control',
            })
    )

    university = forms.ModelChoiceField(
        required=False,
        queryset=University.objects.all(),
        widget=Select(
            attrs={
                'class': 'form-control',
            })
    )


class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'code', 'university', 'description', 'category', 'url', 'prerequisites', 'core_for_major',
                  'last_taught', 'instructor', 'learning_goals', 'equivalent']

    name = forms.CharField(
        widget=TextInput(attrs={
            'class': 'form-control'
        })
    )

    code = forms.CharField(
        widget=TextInput(attrs={
            'class': 'form-control'
        })
    )

    university = forms.ModelChoiceField(
        queryset=University.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='university:auto_complete',
        ),
        help_text="Don't find your university? <a href=\"{}\">Add one.</a>",
    )

    description = forms.CharField(
        widget=Textarea(attrs={
            'class': 'form-control'
        })
    )

    category = forms.ChoiceField(
        choices=choices.CATEGORY_CHOICES,
        widget=Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    url = forms.URLField(
        widget=TextInput(attrs={
            'class': 'form-control'
        })
    )

    prerequisites = forms.CharField(
        widget=TextInput(attrs={
            'class': 'form-control'
        })
    )

    last_taught = forms.DateField(
        widget=MyDateInput()
    )

    instructor = forms.CharField(
        widget=TextInput(attrs={
            'class': 'form-control'
        })
    )

    learning_goals = forms.CharField(
        widget=Textarea(attrs={
            'class': 'form-control'
        })
    )

    equivalent = forms.ModelMultipleChoiceField(
        queryset=Course.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(
            url='course:auto_complete',
            attrs={
                'class': 'form-control',
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['university'].help_text = self.fields['university'].help_text.format(reverse_lazy('university:add'))


class UniversityCreateForm(forms.ModelForm):
    class Meta:
        model = University
        fields = ['name', 'short_name', 'country', 'state', 'city']

    state = forms.ChoiceField(
        choices=get_all_states(),
        widget=autocomplete.Select2(url='university:state_auto_complete', forward=['country'])
    )

message/views.py
# Create your views here.
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView

from message.models import Message


class MessageListView(ListView):
    model = Message
    template_name = 'message/message_list_view.html'

    def get_queryset(self):
        return Message.objects.filter(receiver=self.request.user, read=False).order_by('-pk')


class MessageDetailView(UserPassesTestMixin, ListView):
    model = Message
    template_name = 'message/message_detail_view.html'

    def get_message(self):
        message_id = self.request.GET.get('message', None)
        return get_object_or_404(Message, pk=message_id)

    def test_func(self):
        return self.request.user == self.get_message().receiver

    def get_queryset(self):
        message = self.get_message()
        result = []
        while message is not None:
            message.read_message()
            result.append(message)
            message = message.reply_to
        return result


def message_delete_view(request):
    message = get_object_or_404(Message, pk=request.GET.get('message', None))

    if message.receiver != request.user:
        raise Http404

    message.delete()

    return render(request, 'message.html', {
        'title': 'Message Deleted',
        'message': "Message deleted successfully",
    })

templates/account_message.html
{% extends 'account_base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block form %}
    <div class="form-group">
        <h2>{{ title }}</h2>
    </div>
    <div class="form-group">
        <p>{{ message }}</p>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block" id="menu-toggle"
                onclick="window.location='{% url 'homepage' %}';">Go Home
        </button>
    </div>
{% endblock %}

templates/activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/course_detail_view.html
{% extends 'base.html' %}

{% block title %}Course Detail{% endblock %}

{% block content %}
    <h2>Course</h2>

    <div class="col-md-6 mb-3">
        <label for="University Name">Name</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.name }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="Short Name">Code</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.code }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">University</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.university.name }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="description">Description</label>
        <textarea disabled class="form-control" name="description" cols="40" rows="10" id="description">
            {{ course.description }}
        </textarea>
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Category</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.category }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="id_url">Most Recent Course Website</label>
        <input disabled class="form-control" type="url" name="url"
               value="{{ course.url }}"
               maxlength="200" id="id_url">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Prerequisites</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.prerequisites }}">
    </div>

    <p>
        <label for="id_core_for_major">Core for Major</label>
        <input disabled class="form-control" type="checkbox" name="core_for_major" id="id_core_for_major"
                {% if course.core_for_major %} checked {% endif %}>
    </p>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Last Taught</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.last_taught.year }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="Short Name">Instructor</label>
        <input type="text" disabled class="form-control" id="university-name" placeholder=""
               value="{{ course.instructor }}">
    </div>

    <div class="col-md-6 mb-3">
        <label for="description">Learning Goals / Outcome</label>
        <textarea disabled class="form-control" name="description" cols="40" rows="10" id="description">
            {{ course.learning_goals }}
        </textarea>
    </div>

    <div class="col-md-6 mb-3">
        {% if course.editable %}
            <button class="btn btn-warning"
                    onclick="window.location.href='{% url 'course_update' course.pk %}'">edit
            </button>
        {% else %}
            <button class="btn btn-warning" disabled title="You Cannot Edit This Course"
                    onclick="window.location.href='{% url 'course_update' course.pk %}'">edit
            </button>
        {% endif %}
    </div>




{% endblock %}

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-3" align="center">
            What We Teach
        </h1>
        <h4>A Site to Host and Analyze University Course Syllabi</h4>
        <p>
            This is an online tool to gather, host, and analyze educational patterns in university course syllabi. Using
            the
            syllabus information, we wish to gain a better understanding of topic coverage, theories taught, and
            techniques
            practiced in the classroom. Furthermore, this tool enables regional comparisons of the data in the system.
            Ultimately, we hope to uncover pedagogical choices made in our courses by analyzing syllabi information.
        </p>
    </div>
    <h1>
        Courses
    </h1>

    {% include 'course/course_list_table_snippet.html' with object_list=courses %}

    <div class="container-fluid">
        <div class="row">
            <button class="btn btn-primary mr-1" onclick="window.location.href='{% url 'course:list_view' %}'">Show
                More
            </button>
            <button class="btn btn-primary mr-1" onclick="window.location.href='{% url 'course:add' %}'">Contribute
                a
                Courses
            </button>
        </div>
    </div>

    <h1 class="my-3">
        Charts
    </h1>

    <div style="width: 50%; margin: 0 auto">
        {% include 'charts/criteria_chart_snippet.html' with labels=sample_chart_labels data=sample_chart_data %}
    </div>

    <div class="container-fluid">
        <div class="row">
            <button class="btn btn-primary my-3 mr-1" onclick="window.location.href='{% url 'charts:charts' %}'">Show
                More Charts
            </button>
        </div>
    </div>

{% endblock %}

templates/message.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>{{ title }}</h2>
    <p>{{ message }}</p>

    <button type="submit" class="btn btn-primary btn-block" id="menu-toggle"
            onclick="window.location='{% url 'homepage' %}';">Go Home
    </button>
{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'homepage' %}">
        <img src="{% static 'logo/logo.jpg' %}" width="40" height="40" class="d-inline-block align-top"
             alt="Logo" style="border-radius: 50%">
    </a>
    <a class="navbar-brand" href="{% url 'homepage' %}">What We Teach</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:list_view' %}">Search</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:add' %}">Contribute</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Charts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'charts:charts' %}">Charts</a>
                    <a class="dropdown-item" href="{% url 'charts:criteria' %}">Criteria</a>
                    <a class="dropdown-item" href="{% url 'charts:word_cloud' %}">Word Clouds</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav mr-md-0">
            {% if user.is_authenticated %}
                <span class="navbar-text" style="float: right">
                    Hello, {{ user.first_name | safe }}
                </span>
                <li class="nav-item dropdown" style="float: right">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false" style="float: right">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'message:list_view' %}">Messages</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                    </div>
                </li>
                {% if user.is_staff %}
                    <form class="form-inline" style="margin-left: 5px">
                        <button class="btn btn-outline-success float-right" type="button"
                                onclick="window.location.href ='{% url 'admin:index' %}'">Admin
                        </button>
                    </form>
                {% endif %}
            {% else %}
                <form class="form-inline">
                    <button class="btn btn-outline-success float-right" type="button"
                            onclick="window.location.href ='{% url 'account:signup' %}'">Sign Up
                    </button>
                </form>
                <form class="form-inline" style="margin-left: 5px">
                    <button class="btn btn-outline-success float-right" type="button"
                            onclick="window.location.href ='{% url 'account:login' %}'">Log In
                    </button>
                </form>
            {% endif %}
        </ul>
    </div>
</nav>

templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <h2>Profile</h2>
    <form method="post" style="margin: 10px">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" id="menu-toggle">Update</button>
    </form>
    <button class="btn btn-outline-warning" onclick="window.location='{% url 'password_change' %}';">Change Password</button>
{% endblock %}

templates/sidebar.html
{% load static %}

<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
        <div class="sidebar-brand">
            <a href="#">What We Teach</a>
            <div id="close-sidebar">
                <i class="fas fa-times"></i>
            </div>
        </div>
        <div class="sidebar-header">
            <div class="user-pic">
                <img class="img-responsive img-rounded"
                     src="{% static 'main_page/icon/user.jpg' %}"
                     alt="User picture">
            </div>
            <div class="user-info">
                {% if user.has_name %}
                    <span class="user-name">
                            {{ user.first_name|safe }}
                            <strong>{{ user.last_name|safe }}</strong>
                        </span>
                {% elif user.is_authenticated %}
                    <span class="user-name">
                            {{ user.username|safe }}
                        </span>
                {% else %}
                    <span class="user-name">
                            New
                            <strong>User</strong>
                        </span>
                {% endif %}

                {% if user.is_staff %}
                    <span class="user-role">Administrator</span>
                {% elif user.is_authenticated %}
                    <span class="user-role">User</span>
                {% else %}
                    <span class="user-role"><a href="{% url 'account:login' %}">Login</a></span>
                {% endif %}
                <span class="user-status">
                        {% if user.is_authenticated %}
                            <i class="fa fa-circle"></i>
                            <span>Online</span>
                        {% else %}
                            <i class="fa fa-circle" style="color: red"></i>
                            <span>Offline</span>
                        {% endif %}
                    </span>
            </div>
        </div>
        <!-- sidebar-header  -->
        <div class="sidebar-search">
            <div>
                <div class="input-group">
                    <input type="text" class="form-control search-menu" placeholder="Search...">
                    <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
                    </div>
                </div>
            </div>
        </div>
        <!-- sidebar-search  -->
        <div class="sidebar-menu">
            <ul>
                <li class="header-menu">
                    <span>General</span>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'homepage' %}">Home Page
                                    <span class="badge badge-pill badge-success">Pro</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-university"></i>
                        <span>University</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'university:list_view' %}">Universities

                                </a>
                            </li>
                            <li>
                                <a href="{% url 'university:add' %}">Add a University</a>
                            </li>
                            <li>
                                <a href="{% url 'report:university' %}">Report a University</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-calculator"></i>
                        <span>Course</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'course:list_view' %}">Courses</a>
                            </li>
                            <li>
                                <a href="{% url 'course:add' %}">Add a Course</a>
                            </li>
                            <li>
                                <a href="{% url 'report:course' %}">Report a Course</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-chart-line"></i>
                        <span>Charts</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'charts:word_cloud' %}">Word Clouds</a>
                            </li>
                            <li>
                                <a href="{% url 'charts:charts' %}">Line chart</a>
                            </li>
                            <li>
                                <a href="{% url 'charts:charts' %}">Bar chart</a>
                            </li>
                            <li>
                                <a href="{% url 'charts:charts' %}">Histogram</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fa fa-book"></i>
                        <span>Account</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="{% url 'account:login' %}">Login</a>
                            </li>
                            <li>
                                <a href="{% url 'account:signup' %}">Sign Up</a>
                            </li>
                            <li>
                                <a href="{% url 'account:profile' %}">Profile</a>
                                {% if not user.has_complete_profile %}
                                    <span class="badge badge-pill badge-danger">Uncomplete Profile</span>
                                {% endif %}
                            </li>
                            <li>
                                <a href="{% url 'account:logout' %}">Logout</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="header-menu">
                    <span>Extra</span>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-book"></i>
                        <span>Documentation</span>
                        <span class="badge badge-pill badge-primary">Beta</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-calendar"></i>
                        <span>Calendar</span>
                        <span class="badge badge-pill badge-warning">New</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-folder"></i>
                        <span>Examples</span>
                        <span class="badge badge-pill badge-danger">3</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
        <a href="{% url 'message:list_view' %}">
            <i class="fa fa-bell"></i>
            {% if user.new_messages_count > 0 %}
                <span class="badge badge-pill badge-warning notification">{{ user.new_messages_count }}</span>
            {% endif %}
        </a>
        <a href="{% url 'message:list_view' %}">
            <i class="fa fa-envelope"></i>
            {% if user.new_messages_count > 0 %}
                <span class="badge badge-pill badge-success notification">{{ user.new_messages_count }}</span>
            {% endif %}
        </a>
        <a href="{% url 'account:profile' %}">
            <i class="fa fa-cog"></i>
        </a>
        <a href="{% url 'account:logout' %}">
            <i class="fa fa-power-off"></i>
            {% if user.is_authenticated %}
                <span class="badge-sonar"></span>
            {% endif %}
        </a>
    </div>
</nav>
<!-- sidebar-wrapper  -->